# Exercícios

Noteboook para lista_2 de exercícios da disciplina de introdução à ciência de dados.

autor: Luís Eduardo Cruvinel Pinto  
data: 18/08/2024

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/luiscruvinel/exercicios/blob/main/lista2.ipynb)

In [ ]:
import numpy as np
import pandas as pd

### Exercício-001
Crie uma matriz 3x3 com valores variando de 0 a 8:

In [216]:
array = np.random.randint(0, 9, size = (3,3))
print(array)

[[3 1 4]
 [3 7 4]
 [8 3 8]]


### Exercício-002
Adicione uma borda ao redor de uma matriz numpy. Utilize _fancy indexing_.

In [222]:
def bordeador(matriz):
    rows, collumns = matriz.shape
    
    matriz_com_borda = np.zeros((rows+2, collumns+2), dtype = matriz.dtype)
    matriz_com_borda[1:-1, 1:-1] = matriz

    return matriz_com_borda

if __name__ == '__main__':
    matriz_exemplo = np.random.randint(1,10, (3,3))
    print('Aqui está uma matriz exemplo: ')
    print(matriz_exemplo, '\n')

    print('Aqui está a matriz exemplo com borda: ')
    print(bordeador(matriz_exemplo))


Aqui está uma matriz exemplo: 
[[5 8 8]
 [1 9 5]
 [2 3 5]] 

Aqui está a matriz exemplo com borda: 
[[0 0 0 0 0]
 [0 5 8 8 0]
 [0 1 9 5 0]
 [0 2 3 5 0]
 [0 0 0 0 0]]


### Exercício-003
Mude a escala uma matriz numpy de dimensões 5x5 com a seguinte formulação:

$z=\frac{x_i-\bar{x}}{std(x)}$

In [226]:
import numpy as np
# np.random.seed(0)

def convert_to_zscore(array):
    mean = array.mean()
    std = array.std()

    new_array = (array-mean)/std
    return new_array


if __name__ == '__main__':
    test_array = np.random.uniform(0,10, size = (5,5))
    z_array = convert_to_zscore(test_array)
    
    print('Este é o array aleatoriamente gerado: ')
    print(test_array)
    print()
    print('Este é o array convertido a Z-scores')
    print(z_array)

Este é o array aleatoriamente gerado: 
[[6.30813721 1.15609656 5.68480072 1.45284734 9.94708555]
 [9.09143568 6.0315453  7.54775095 9.59984555 1.7824146 ]
 [3.83712906 4.60466555 2.08134249 7.92114327 5.13011462]
 [3.75975553 0.15303479 0.95624566 1.40628221 6.58238806]
 [7.94299848 0.14095476 6.78725183 1.18587146 0.46635526]]

Este é o array convertido a Z-scores
[[ 0.58542108 -1.04858688  0.38772528 -0.95447017  1.73954057]
 [ 1.46816486  0.4976979   0.97857378  1.62941083 -0.84994546]
 [-0.19827751  0.04515239 -0.75513826  1.09699793  0.21180246]
 [-0.2228171  -1.36671537 -1.11197108 -0.96923865  0.67240177]
 [ 1.10392947 -1.37054664  0.73737584 -1.03914355 -1.26734346]]


### Exercício-004
Crie um `array` numpy aleatório com 10 elementos e ordene utilizando um método da biblioteca numpy.


In [231]:
array = np.random.randint(0, 10, (2,5))
print(array)

ordered_array = np.sort(array, axis = 1)
print(ordered_array)

[[0 6 2 3 1]
 [6 0 7 6 8]]
[[0 1 2 3 6]
 [0 6 6 7 8]]


### Exercícios-005
Considerando 2 `arrays` numpy unidimensionais com 10 valores execute as operações: `np.sum(A)`, `A * B`, `np.inner(A, B)`, `np.outer(A, B)`


e explique o funcionamento de cada operação

In [235]:
print('Aqui está uma matriz exemplo chamada matriz_a: ')
matriz_a = np.arange(1, 11, 1)
print(matriz_a, '\n')

print('Aqui está outra matriz exemplo chamada matriz_b: ')
matriz_b = np.arange(11, 21, 1)
print(matriz_b, '\n')

print('A função np.sum() retorna o somatório de todos os valores presentes em uma matriz, a menos que especificado um eixo: ')
print(f'np.sum(matriz_a) == {np.sum(matriz_a)}\nnp.sum(matriz_b) == {np.sum(matriz_b)}\n')

print('A operação de multiplicação retorna uma terceira matriz com o valor correspondente da multiplicação de cada índice: \nNote que é diferente da operação matemática "multiplicação de matrizes": ')
print(f'matriz_a * matriz_b == {matriz_a * matriz_b}')

print('\nAs funções np.inner() e np.outer() retornam os produtos interno e externo/vetorial de uma matriz, respectivamente: ')
print(f'np.inner(matriz_a, matriz_b) == {np.inner(matriz_a, matriz_b)} --> o resultado sempre será um escalar.')
print(f'np.outer(matriz_a, matriz_b) == \n{np.outer(matriz_a, matriz_b)}')

# produto interno [a, b, c] * [d, e, f] = a*d + b*e + c*f
# produto externo

Aqui está uma matriz exemplo chamada matriz_a: 
[ 1  2  3  4  5  6  7  8  9 10] 

Aqui está outra matriz exemplo chamada matriz_b: 
[11 12 13 14 15 16 17 18 19 20] 

A função np.sum() retorna o somatório de todos os valores presentes em uma matriz, a menos que especificado um eixo: 
np.sum(matriz_a) == 55
np.sum(matriz_b) == 155

A operação de multiplicação retorna uma terceira matriz com o valor correspondente da multiplicação de cada índice: 
Note que é diferente da operação matemática "multiplicação de matrizes": 
matriz_a * matriz_b == [ 11  24  39  56  75  96 119 144 171 200]

As funções np.inner() e np.outer() retornam os produtos interno e externo/vetorial de uma matriz, respectivamente: 
np.inner(matriz_a, matriz_b) == 935 --> o resultado sempre será um escalar.
np.outer(matriz_a, matriz_b) == 
[[ 11  12  13  14  15  16  17  18  19  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 33  36  39  42  45  48  51  54  57  60]
 [ 44  48  52  56  60  64  68  72  76  80]
 [ 55  60  65 

### Exercícios-006
Crie uma matriz no formato 10x3, extraia linhas com valores diferentes (exemplo: `[2, 2, 3]`):

In [240]:
def find_wally(array):
    rows_to_delete = []

    for i, row in enumerate(array):
        if len(set(row)) > 1:
            print(row)
            rows_to_delete.append(i)
    
    new_array = np.delete(array, rows_to_delete, axis = 0)
    print('\nAqui está a matriz sem o intruso:')
    print(new_array)

if __name__ == '__main__':
    import random
    matriz_exemplo = np.array([[i, i, i] for i in range(1,11)])

    # Substituir um elemento aleatório por zero:
    rows, cols = matriz_exemplo.shape
    random_row = random.randint(0, rows-1)
    random_col = random.randint(0, cols-1)
    matriz_exemplo[random_row, random_col] = 0
    print('Aqui está a matriz 10x3:\nUm dos elementos foi substituído por "0" aleatoriamente.')
    print(matriz_exemplo)
    print('\nAgora vamos encontrar onde está o intruso!"')
    find_wally(matriz_exemplo)



Aqui está a matriz 10x3:
Um dos elementos foi substituído por "0" aleatoriamente.
[[ 0  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [ 4  4  4]
 [ 5  5  5]
 [ 6  6  6]
 [ 7  7  7]
 [ 8  8  8]
 [ 9  9  9]
 [10 10 10]]

Agora vamos encontrar onde está o intruso!"
[0 1 1]

Aqui está a matriz sem o intruso:
[[ 2  2  2]
 [ 3  3  3]
 [ 4  4  4]
 [ 5  5  5]
 [ 6  6  6]
 [ 7  7  7]
 [ 8  8  8]
 [ 9  9  9]
 [10 10 10]]


### Exercícios-007
Crie duas matrizes com números aleatórios no formato 2x3, e multiplique a primeira matriz pela transposta da segunda. Explique como o resultado da multiplicação das matrizes foi obtido.

In [243]:
np.random.seed(0)

matriz_a = np.random.randint(1, 7, (2,3))
matriz_b = np.random.randint(1, 7, (2,3))

print('\nAqui está a primeira matriz 2x3 aleatória: ')
print(matriz_a)

print('\nAqui está a segunda matriz 2x3 aleatória: ')
print(matriz_b)

print('\nAqui está a segunda matriz transposta, \nEla foi obtida transformando as linhas em colunas e as colunas em linhas: ')
print(matriz_b.transpose())

print('\nAqui está o resultado da multiplicação: ')
print(np.matmul(matriz_a, matriz_b.transpose()))

print('''\nEla foi obtida através da operação matemática de multiplicação de matrizes, 
em que cada posição LxC (linha x coluna) corresponde ao somatório da multiplicação das colunas 
da primeira matriz pelas linhas da segunda matriz''')


Aqui está a primeira matriz 2x3 aleatória: 
[[5 6 1]
 [4 4 4]]

Aqui está a segunda matriz 2x3 aleatória: 
[[2 4 6]
 [3 5 1]]

Aqui está a segunda matriz transposta, 
Ela foi obtida transformando as linhas em colunas e as colunas em linhas: 
[[2 3]
 [4 5]
 [6 1]]

Aqui está o resultado da multiplicação: 
[[40 46]
 [48 36]]

Ela foi obtida através da operação matemática de multiplicação de matrizes, 
em que cada posição LxC (linha x coluna) corresponde ao somatório da multiplicação das colunas 
da primeira matriz pelas linhas da segunda matriz


### Exercício-008

Calcule o percentil de 80% no segundo eixo (_axis_) de uma matriz numpy.

In [245]:
np.random.seed(0)

matriz = np.random.uniform(1, 50, size = (5,5))

print('Aqui está uma matriz 5x5 aleatória: ')
print(matriz)

print(f'\nAqui está o p80 no segundo eixo: p80 == {np.percentile(matriz, 80, axis=1)}')

Aqui está uma matriz 5x5 aleatória: 
[[27.89186169 36.04427895 30.53540543 27.69927597 21.75908517]
 [32.64881154 22.44177335 44.69687704 48.21947526 19.78863442]
 [39.79452687 26.91585107 28.83418349 46.35423528  4.48076685]
 [ 5.26933569  1.99070147 41.79837243 39.1296808  43.63059526]
 [48.95229877 40.15876965 23.61248875 39.24592964  6.79544687]]

Aqui está o p80 no segundo eixo: p80 == [31.63718013 45.40139668 41.10646855 42.164817   41.91747547]


### Exercício-009

Crie um programa utilizando pandas para disponibilizar um sumário básico de informações contidas em um _dataframe_:

Informações que devem constar no _dataframe_:

nome - ['Ana', 'Dilma', 'Catarina', 'João', 'Emilia', 'Michel', 'Mateus','Laura', 'Kevin', 'Jonas']

nota - [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19]

tentativas - [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]

qualicacao - ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']

rotulos - ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [247]:
alunos = pd.DataFrame({
    'nome' : ['Ana', 'Dilma', 'Catarina', 'João', 'Emilia', 'Michel', 'Mateus','Laura', 'Kevin', 'Jonas'],
    'nota' : [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'tentativas' : [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualificacao' : ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'rotulos' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
})

display(alunos)

nome  nota  tentativas qualificacao rotulos
0       Ana  12.5           1          yes       a
1     Dilma   9.0           3           no       b
2  Catarina  16.5           2          yes       c
3      João   NaN           3           no       d
4    Emilia   9.0           2           no       e
5    Michel  20.0           3          yes       f
6    Mateus  14.5           1          yes       g
7     Laura   NaN           1           no       h
8     Kevin   8.0           2           no       i
9     Jonas  19.0           1          yes       j

### Exercício-010
Escreva num programa para encontras os _n_ menores valores em um _dataframe_ pandas.

In [250]:
def menores_valores(dataframe, n):
    array = dataframe.to_numpy()
    sortedarray = np.sort(array.flatten())
    
    return sortedarray[:n]

# Poderia usar também: print(df.stack().nsmallest(3))

if __name__ == '__main__':
    df = pd.DataFrame(np.random.randint(0, 100, size=(5, 4)), columns = list('ABCD'))
    print('Aqui está um dataframe aleatório: ')
    display(df)

    print('Aqui estão os 3 menores valores do dataframe: ')
    print(menores_valores(df, 3))
    # Poderia usar também: 
    # print(df.stack().nsmallest(3)) # -> retorna os menores valores COM posição na tabela




Aqui está um dataframe aleatório: 


A   B   C   D
0  84  75  68   6
1  68  47   3  76
2  52  78  15  20
3  99  58  23  79
4  13  85  48  49

Aqui estão os 3 menores valores do dataframe: 
[ 3  6 13]


### Exercício-011
Escreva um programa para encontrar dentro de um intervalo fixado (exemplo: $a<x<b$) e substituí-los por 0.

In [253]:
def replace_by_zero(dataframe, lower, upper):
    dataframe[(dataframe >=lower) & (dataframe <= upper)] = 0
    return dataframe


if __name__ == '__main__':
    print('Aqui está um dataframe aleatório: ')
    df = pd.DataFrame(np.random.randint(0, 100, size=(5, 4)), columns = list('ABCD'))
    display(df)

    print('Aqui está o dataframe com números entre 20 e 80 substituídos por 0: ')
    display(replace_by_zero(df, 20, 80))


Aqui está um dataframe aleatório: 


A   B   C   D
0  58  65  36  10
1  86  43  11   2
2  51  80  32  54
3   0  38  19  46
4  42  56  60  77

Aqui está o dataframe com números entre 20 e 80 substituídos por 0: 


A  B   C   D
0   0  0   0  10
1  86  0  11   2
2   0  0   0   0
3   0  0  19   0
4   0  0   0   0

### Exercício-012
Utilize os métodos `max` para encontrar o máximo de uma coluna em _dataframe_ pandas e depois `query` para encontrar onde os valores na coluna referida são menores que o máximo.

In [266]:
def lower_than_max(dataframe, coluna):
    max_value = (dataframe.max()[coluna])
    print(f'O valor máximo em {coluna} é: {max_value}')
    print(f'Aqui estão as linhas onde o valor em {coluna} é menor que o máximo:\n')
    display(dataframe.query(f'{coluna} < @max_value'))

if __name__ == '__main__':
    print('Aqui está um dataframe aleatório: ')
    df = pd.DataFrame(np.random.randint(0, 100, size=(5, 4)), columns = ['coluna_A','coluna_B','coluna_C','coluna_D'])
    display(df)

    lower_than_max(df, 'coluna_A')

Aqui está um dataframe aleatório: 


coluna_A  coluna_B  coluna_C  coluna_D
0        58        43        55        18
1        45        87        65        70
2        53        48        94        59
3        80        26        35        58
4        49        73        44        13

O valor máximo em coluna_A é: 80
Aqui estão as linhas onde o valor em coluna_A é menor que o máximo:



coluna_A  coluna_B  coluna_C  coluna_D
0        58        43        55        18
1        45        87        65        70
2        53        48        94        59
4        49        73        44        13

### Exercício-013
Remova os espaços na extremidade dos nomes das colunas e transforme em minúsculo utilizando o método `.str` para o conjunto de dados listado abaixo.

In [270]:
df = pd.DataFrame({
    'Nome': ['Alberto Franco','Giovane Pereira','Reinaldo Oliveira', 'Elen Cavalcanti', 'Paulo Freire'],
    'Data_de_Nascimento ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Idade': [18.5, 21.2, 22.5, 22, 23]
})

print('Dataframe original: ')
display(df)

df.columns = df.columns.str.lower().str.strip(' ').str.replace(' ', '_')
print('Dataframe com colunas formatadas:')
display(df)

Dataframe original: 


Nome Data_de_Nascimento   Idade
0     Alberto Franco          17/05/2002   18.5
1    Giovane Pereira          16/02/1999   21.2
2  Reinaldo Oliveira          25/09/1998   22.5
3    Elen Cavalcanti          11/05/2002   22.0
4       Paulo Freire          15/09/1997   23.0

Dataframe com colunas formatadas:


nome data_de_nascimento  idade
0     Alberto Franco         17/05/2002   18.5
1    Giovane Pereira         16/02/1999   21.2
2  Reinaldo Oliveira         25/09/1998   22.5
3    Elen Cavalcanti         11/05/2002   22.0
4       Paulo Freire         15/09/1997   23.0

### Exercício-014
Preencha os dados de um _dataframe_ nas posições em que os dados são nulos com um segundo _dataframe_ para o conjunto de dados listado abaixo.

In [273]:
df1 = pd.DataFrame({'A': [None, 0, None], 'B': [3, 4, 5]})
df2 = pd.DataFrame({'A': [1, 1, 3], 'B': [3, None, 3]})

print('Aqui estão os dataframes originais: ')
display(df1, df2)

df1 = df1.fillna(df2)
df2 = df2.fillna(df1)

print('Aqui estão os dataframes com seus nulos substituídos: ')
display(df1, df2)

Aqui estão os dataframes originais: 


A  B
0  NaN  3
1  0.0  4
2  NaN  5

A    B
0  1  3.0
1  1  NaN
2  3  3.0

Aqui estão os dataframes com seus nulos substituídos: 


A  B
0  1.0  3
1  0.0  4
2  3.0  5

A    B
0  1  3.0
1  1  4.0
2  3  3.0

### Exercício-015
Escreva um programa que primeiro concatena dois _dataframe_ e depois faz operação de união (`merge`) com um terceiro em uma coluna especificada para o conjunto de dados listado abaixo.

In [298]:
dados_estudante1 = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Daniela', 'Riobaldo', 'Bruno', 'Eduardo', 'Monica'],
        'notas': [200, 210, 190, 222, 199]})

dados_estudante2 = pd.DataFrame({
        'codigo': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Isabela', 'Carla', 'Denise', 'Carmen', 'Madalena'],
        'notas': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'id_prova': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

todos_estudantes = pd.concat((dados_estudante1, dados_estudante2)).reset_index(drop=True)
full_data = pd.merge(todos_estudantes, exam_data, on='codigo', how='inner') # especificando on e inner apenas para deixar claro
display(full_data)

codigo      name  notas  id_prova
0     S1   Daniela    200        23
1     S2  Riobaldo    210        45
2     S3     Bruno    190        12
3     S4   Eduardo    222        67
4     S5    Monica    199        21
5     S4   Isabela    201        67
6     S5     Carla    200        21
7     S7    Carmen    219        55
8     S8  Madalena    201        33

### Exercício-016
Escreva um programa que faz operação de união (`merge`) utilizando mais de uma coluna para o conjunto de dados listado abaixo.

In [299]:
data1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'P': ['P0', 'P1', 'P2', 'P3'],
                     'Q': ['Q0', 'Q1', 'Q2', 'Q3']})
data2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'R': ['R0', 'R1', 'R2', 'R3'],
                      'S': ['S0', 'S1', 'S2', 'S3']})

display(data1, data2)

data3 = pd.merge(data1, data2, on = ['key1', 'key2'])
display(data3)

key1 key2   P   Q
0   K0   K0  P0  Q0
1   K0   K1  P1  Q1
2   K1   K0  P2  Q2
3   K2   K1  P3  Q3

key1 key2   R   S
0   K0   K0  R0  S0
1   K1   K0  R1  S1
2   K1   K0  R2  S2
3   K2   K0  R3  S3

key1 key2   P   Q   R   S
0   K0   K0  P0  Q0  R0  S0
1   K1   K0  P2  Q2  R1  S1
2   K1   K0  P2  Q2  R2  S2