In [33]:
import numpy as np

### Exercício-001
Crie uma matriz 3x3 com valores variando de 0 a 8:

In [ ]:
array = np.random.uniform(0, 9, size = (3,3))
print(array)

### Exercício-002
Adicione uma borda ao redor de uma matriz numpy. Utilize _fancy indexing_.

In [40]:
def bordeador(matriz):
    rows, collumns = matriz.shape
    
    matriz_com_borda = np.zeros((rows+2, collumns+2), dtype = matriz.dtype)
    matriz_com_borda[1:-1, 1:-1] = matriz

    return matriz_com_borda

if __name__ == '__main__':
    matriz_exemplo = np.random.randint(1,10, (3,3))
    print('Aqui está uma matriz exemplo: ')
    print(matriz_exemplo, '\n')

    print('Aqui está a matriz exemplo com borda: ')
    print(bordeador(matriz_exemplo))


Aqui está uma matriz exemplo: 
[[3 2 2]
 [3 2 4]
 [7 7 9]] 

Aqui está a matriz exemplo com borda: 
[[0 0 0 0 0]
 [0 3 2 2 0]
 [0 3 2 4 0]
 [0 7 7 9 0]
 [0 0 0 0 0]]


### Exercício-003
Mude a escala uma matriz numpy de dimensões 5x5 com a seguinte formulação:

$z=\frac{x_i-\bar{x}}{std(x)}$

In [41]:
import numpy as np
np.random.seed(0)

array = np.random.uniform(0,10, size = (5,5))

mean = array.mean()
std = array.std()

new_array = (array-mean)/std

print('Este é o array aleatoriamente gerado: ')
print(array)
print()
print('Este é o array convertido a Z-scores')
print(new_array)

Este é o array aleatoriamente gerado: 
[[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799]
 [6.45894113 4.37587211 8.91773001 9.63662761 3.83441519]
 [7.91725038 5.2889492  5.68044561 9.25596638 0.71036058]
 [0.871293   0.20218397 8.32619846 7.78156751 8.70012148]
 [9.78618342 7.99158564 4.61479362 7.80529176 1.18274426]]

Este é o array convertido a Z-scores
[[-0.14854421  0.44055117  0.04247881 -0.1624605  -0.59169993]
 [ 0.19519398 -0.54236874  1.06578972  1.32033341 -0.73408512]
 [ 0.71154487 -0.21907095 -0.08045184  1.18555078 -1.84023484]
 [-1.78325269 -2.02016749  0.85634317  0.66350295  0.98873998]
 [ 1.37328739  0.73786513 -0.4577726   0.67190312 -1.67297558]]


### Exercício-004
Crie um `array` numpy aleatório com 10 elementos e ordene utilizando um método da biblioteca numpy.


In [46]:
array = np.random.randint(0, 10, (2,5))
print(array)

ordered_array = np.sort(array)
print(ordered_array)

[[4 3 4 4 8]
 [4 3 7 5 5]]
[[3 4 4 4 8]
 [3 4 5 5 7]]


### Exercícios-005
Considerando 2 `arrays` numpy unidimensionais com 10 valores execute as operações: `np.sum(A)`, `A * B`, `np.inner(A, B)`, `np.outer(A, B)`


e explique o funcionamento de cada operação

In [63]:
print('Aqui está uma matriz exemplo chamada matriz_a: ')
matriz_a = np.arange(1, 11, 1)
print(matriz_a, '\n')

print('Aqui está outra matriz exemplo chamada matriz_b: ')
matriz_b = np.arange(11, 21, 1)
print(matriz_b, '\n')

print('A função np.sum() retorna o somatório de todos os valores presentes em uma matriz, a menos que especificado um eixo: ')
print(f'np.sum(matriz_a) == {np.sum(matriz_a)}\nnp.sum(matriz_b) == {np.sum(matriz_b)}\n')

print('A operação de multiplicação retorna uma terceira matriz com o valor correspondente da multiplicação de cada índice: \nNote que é diferente da operação matemática "multiplicação de matrizes": ')
print(f'matriz_a * matriz_b == {matriz_a * matriz_b}')

print('\nAs funções np.inner() e np.outer() retornam os produtos interno e externo/vetorial de uma matriz, respectivamente: ')
print(f'np.inner(matriz_a, matriz_b) == {np.inner(matriz_a, matriz_b)} --> o resultado sempre será um escalar.')
print(f'np.outer(matriz_a, matriz_b) == \n{np.outer(matriz_a, matriz_b)}')

# produto interno [a, b, c] * [d, e, f] = a*d + b*e + c*f
# produto externo

Aqui está uma matriz exemplo chamada matriz_a: 
[ 1  2  3  4  5  6  7  8  9 10] 

Aqui está outra matriz exemplo chamada matriz_b: 
[11 12 13 14 15 16 17 18 19 20] 

A função np.sum() retorna o somatório de todos os valores presentes em uma matriz: 
np.sum(matriz_a) == 55
np.sum(matriz_b) == 155

A operação de multiplicação retorna uma terceira matriz com o valor correspondente da multiplicação de cada índice: 
Note que é diferente da operação matemática "multiplicação de matrizes": 
matriz_a * matriz_b == [ 11  24  39  56  75  96 119 144 171 200]

As funções np.inner() e np.outer() retornam os produtos interno e externo/vetorial de uma matriz, respectivamente: 
np.inner(matriz_a, matriz_b) == 935 --> o resultado sempre será um escalar.
np.outer(matriz_a, matriz_b) == 
[[ 11  12  13  14  15  16  17  18  19  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 33  36  39  42  45  48  51  54  57  60]
 [ 44  48  52  56  60  64  68  72  76  80]
 [ 55  60  65  70  75  80  85  90  95 100]
 [ 66

### Exercícios-006
Crie uma matriz no formato 10x3, extraia linhas com valores diferentes (exemplo: `[2, 2, 3]`):

In [49]:
matriz_exemplo = np.random.randint(1, 31, (10,3))
print('Aqui está a matriz 10x3: ')
print(matriz_exemplo)

# O que é pra fazer???

Aqui está a matriz 10x3: 
[[26  3  4]
 [28  4 19]
 [15  4 21]
 [18 19 28]
 [15 10 27]
 [ 2  5 11]
 [23 12  9]
 [12  3 20]
 [17  1 23]
 [ 1  7 20]]


### Exercícios-007
Crie duas matrizes com números aleatórios no formato 2x3, e multiplique a primeira matriz pela transposta da segunda. Explique como o resultado da multiplicação das matrizes foi obtido.

In [71]:
np.random.seed(0)

matriz_a = np.random.randint(1, 7, (2,3))
matriz_b = np.random.randint(1, 7, (2,3))

print('\nAqui está a primeira matriz 2x3 aleatória: ')
print(matriz_a)

print('\nAqui está a segunda matriz 2x3 aleatória: ')
print(matriz_b)

print('\nAqui está a segunda matriz transposta, \nEla foi obtida transformando as linhas em colunas e as colunas em linhas: ')
print(matriz_b.transpose())

print('\nAqui está o resultado da multiplicação: ')
print(np.matmul(matriz_a, matriz_b.transpose()))

print('''\nEla foi obtida através da operação matemática de multiplicação de matrizes, 
em que cada posição LxC (linha x coluna) corresponde ao somatório da multiplicação das colunas 
da primeira matriz pelas linhas da segunda matriz''')


Aqui está a primeira matriz 2x3 aleatória: 
[[5 6 1]
 [4 4 4]]

Aqui está a segunda matriz 2x3 aleatória: 
[[2 4 6]
 [3 5 1]]

Aqui está a segunda matriz transposta, 
Ela foi obtida transformando as linhas em colunas e as colunas em linhas: 
[[2 3]
 [4 5]
 [6 1]]

Aqui está o resultado da multiplicação: 
[[40 46]
 [48 36]]

Ela foi obtida através da operação matemática de multiplicação de matrizes, 
em que cada posição LxC (linha x coluna) corresponde ao somatório da multiplicação das colunas 
da primeira matriz pelas linhas da segunda matriz


### Exercício-008

Calcule o percentil de 80% no segundo eixo (_axis_) de uma matriz numpy.

In [79]:
np.random.seed(0)

matriz = np.random.uniform(1, 50, size = (5,5))

print('Aqui está uma matriz 5x5 aleatória: ')
print(matriz)

print(f'\nAqui está o p80 no segundo eixo: p80 == {np.percentile(matriz, 80, 1)}')

Aqui está uma matriz 5x5 aleatória: 
[[27.89186169 36.04427895 30.53540543 27.69927597 21.75908517]
 [32.64881154 22.44177335 44.69687704 48.21947526 19.78863442]
 [39.79452687 26.91585107 28.83418349 46.35423528  4.48076685]
 [ 5.26933569  1.99070147 41.79837243 39.1296808  43.63059526]
 [48.95229877 40.15876965 23.61248875 39.24592964  6.79544687]]

Aqui está o p80 no segundo eixo: p80 == [31.63718013 45.40139668 41.10646855 42.164817   41.91747547]


### Exercício-009

Crie um programa utilizando pandas para disponibilizar um sumário básico de informações contidas em um _dataframe_:

Informações que devem constar no _dataframe_:

nome - ['Ana', 'Dilma', 'Catarina', 'João', 'Emilia', 'Michel', 'Mateus','Laura', 'Kevin', 'Jonas']

nota - [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19]

tentativas - [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]

qualicacao - ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']

rotulos - ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### Exercício-010
Escreva num programa para encontras os _n_ menores valores em um _dataframe_ pandas.

### Exercício-011
Escreva um programa para encontrar dentro de um intervalo fixado (exemplo: $a<x<b$) e substituí-los por 0.

### Exercício-012
Utilize os métodos `max` para encontrar o máximo de uma coluna em _dataframe_ pandas e depois `query` para encontrar onde os valores na coluna referida são menores que o máximo.

### Exercício-013
Remova os espaços na extremidade dos nomes das colunas e transforme em minúsculo utilizando o método `.str` para o conjunto de dados listado abaixo.

In [ ]:
df = pd.DataFrame({
    'Nome': ['Alberto Franco','Giovane Pereira','Reinaldo Oliveira', 'Elen Cavalcanti', 'Paulo Freire'],
    'Data_de_Nascimento ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Idade': [18.5, 21.2, 22.5, 22, 23]
})

### Exercício-014
Preencha os dados de um _dataframe_ nas posições em que os dados são nulos com um segundo _dataframe_ para o conjunto de dados listado abaixo.

In [ ]:
df1 = pd.DataFrame({'A': [None, 0, None], 'B': [3, 4, 5]})
df2 = pd.DataFrame({'A': [1, 1, 3], 'B': [3, None, 3]})

### Exercício-015
Escreva um programa que primeiro concatena dois _dataframe_ e depois faz operação de união (`merge`) com um terceiro em uma coluna especificada para o conjunto de dados listado abaixo.

In [ ]:
dados_estudante1 = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Daniela', 'Riobaldo', 'Bruno', 'Eduardo', 'Monica'],
        'notas': [200, 210, 190, 222, 199]})

dados_estudante2 = pd.DataFrame({
        'codigo': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Isabela', 'Carla', 'Denise', 'Carmen', 'Madalena'],
        'notas': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'id_prova': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

### Exercício-016
Escreva um programa que faz operação de união (`merge`) utilizando mais de uma coluna para o conjunto de dados listado abaixo.

In [ ]:
import pandas as pd
data1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'P': ['P0', 'P1', 'P2', 'P3'],
                     'Q': ['Q0', 'Q1', 'Q2', 'Q3']})
data2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'R': ['R0', 'R1', 'R2', 'R3'],
                      'S': ['S0', 'S1', 'S2', 'S3']})