### Exercício-001
Crie uma matriz 3x3 com valores variando de 0 a 8:

In [5]:
import numpy as np

array = np.random.uniform(0, 9, size = (3,3))
print(array)

[[5.12715683 3.0630252  6.12504707]
 [1.6317974  7.33522307 0.8447333 ]
 [8.03878793 8.38965327 1.36400544]]


### Exercício-002
Adicione uma borda ao redor de uma matriz numpy. Utilize _fancy indexing_.

### Exercício-003
Mude a escala uma matriz numpy de dimensões 5x5 com a seguinte formulação:

$z=\frac{x_i-\bar{x}}{std(x)}$

In [14]:
import numpy as np
np.random.seed(0)

array = np.random.uniform(0,10, size = (5,5))

mean = array.mean()
std = array.std()

new_array = (array-mean)/std

print('Este é o array aleatoriamente gerado: ')
print(array)
print()
print('Este é o array convertido a Z-scores')
print(new_array)

Este é o array aleatoriamente gerado: 
[[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799]
 [6.45894113 4.37587211 8.91773001 9.63662761 3.83441519]
 [7.91725038 5.2889492  5.68044561 9.25596638 0.71036058]
 [0.871293   0.20218397 8.32619846 7.78156751 8.70012148]
 [9.78618342 7.99158564 4.61479362 7.80529176 1.18274426]]

Este é o array convertido a Z-scores
[[-0.14854421  0.44055117  0.04247881 -0.1624605  -0.59169993]
 [ 0.19519398 -0.54236874  1.06578972  1.32033341 -0.73408512]
 [ 0.71154487 -0.21907095 -0.08045184  1.18555078 -1.84023484]
 [-1.78325269 -2.02016749  0.85634317  0.66350295  0.98873998]
 [ 1.37328739  0.73786513 -0.4577726   0.67190312 -1.67297558]]


### Exercício-004
Crie um `array` numpy aleatório com 10 elementos e ordene utilizando um método da biblioteca numpy.


In [12]:
array = np.random.uniform(0, 10, 10)
print(array)

ordered_array = np.sort(array)
print(ordered_array)

[8.74153963 9.80616208 3.81638833 0.4229492  1.61932027 3.7453416
 7.21575196 2.8931531  3.26379382 6.49804111]
[0.4229492  1.61932027 2.8931531  3.26379382 3.7453416  3.81638833
 6.49804111 7.21575196 8.74153963 9.80616208]


### Exercícios-005
Considerando 2 `arrays` numpy unidimensionais com 10 valores execute as operações: `np.sum(A)`, `A * B`, `np.inner(A, B)`, `np.outer(A, B)`


e explique o funcionamento de cada operação

### Exercícios-006
Crie uma matriz no formato 10x3, extraia linhas com valores diferentes (exemplo: `[2, 2, 3]`):

### Exercícios-007
Crie duas matrizes com números aleatórios no formato 2x3, e multiplique a primeira matriz pela transposta da segunda. Explique como o resultado da multiplicação das matrizes foi obtido.

### Exercício-008

Calcule o percentil de 80% no segundo eixo (_axis_) de uma matriz numpy.

### Exercício-009

Crie um programa utilizando pandas para disponibilizar um sumário básico de informações contidas em um _dataframe_:

Informações que devem constar no _dataframe_:

nome - ['Ana', 'Dilma', 'Catarina', 'João', 'Emilia', 'Michel', 'Mateus','Laura', 'Kevin', 'Jonas']

nota - [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19]

tentativas - [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]

qualicacao - ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']

rotulos - ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### Exercício-010
Escreva num programa para encontras os _n_ menores valores em um _dataframe_ pandas.

### Exercício-011
Escreva um programa para encontrar dentro de um intervalo fixado (exemplo: $a<x<b$) e substituí-los por 0.

### Exercício-012
Utilize os métodos `max` para encontrar o máximo de uma coluna em _dataframe_ pandas e depois `query` para encontrar onde os valores na coluna referida são menores que o máximo.

### Exercício-013
Remova os espaços na extremidade dos nomes das colunas e transforme em minúsculo utilizando o método `.str` para o conjunto de dados listado abaixo.

In [ ]:
df = pd.DataFrame({
    'Nome': ['Alberto Franco','Giovane Pereira','Reinaldo Oliveira', 'Elen Cavalcanti', 'Paulo Freire'],
    'Data_de_Nascimento ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Idade': [18.5, 21.2, 22.5, 22, 23]
})

### Exercício-014
Preencha os dados de um _dataframe_ nas posições em que os dados são nulos com um segundo _dataframe_ para o conjunto de dados listado abaixo.

In [ ]:
df1 = pd.DataFrame({'A': [None, 0, None], 'B': [3, 4, 5]})
df2 = pd.DataFrame({'A': [1, 1, 3], 'B': [3, None, 3]})

### Exercício-015
Escreva um programa que primeiro concatena dois _dataframe_ e depois faz operação de união (`merge`) com um terceiro em uma coluna especificada para o conjunto de dados listado abaixo.

In [ ]:
dados_estudante1 = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Daniela', 'Riobaldo', 'Bruno', 'Eduardo', 'Monica'],
        'notas': [200, 210, 190, 222, 199]})

dados_estudante2 = pd.DataFrame({
        'codigo': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Isabela', 'Carla', 'Denise', 'Carmen', 'Madalena'],
        'notas': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'id_prova': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

### Exercício-016
Escreva um programa que faz operação de união (`merge`) utilizando mais de uma coluna para o conjunto de dados listado abaixo.

In [ ]:
import pandas as pd
data1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'P': ['P0', 'P1', 'P2', 'P3'],
                     'Q': ['Q0', 'Q1', 'Q2', 'Q3']})
data2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'R': ['R0', 'R1', 'R2', 'R3'],
                      'S': ['S0', 'S1', 'S2', 'S3']})